#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'

Fixtures::dump(Screen)
Fixtures::dump(Row)
Fixtures::dump(Cell)
Fixtures::dump(Field)
Fixtures::dump(CustomField)
Fixtures::dump(FieldType)
Fixtures::dump(Label)
Fixtures::dump(Language)
Fixtures::dump(Caption)
Fixtures::dump(User)